### ISSUE TITLE
File names not descriptive enough

### ISSUE THREAD

**Issue by Harvie** [amberspyglass/parts#2]
When i need to find drawing of some part i have to open all DWGs and go through them.
Can you please make them more descriptive. Something like `eshapeoko-carriage-plate-rev-4.dwg` would be easier to decode than `EM-LMP-rev-4.dwg`. I guess you already have some naming convention. Maybe just explaining it in README.md would be sufficient for us to quickly find the right drawing...

**Comment by cvoinescu** [comment]
That is a good point.

However, the file names are the part numbers, and the eShapeoko assembly instructions and packing lists reference parts by their part numbers, so the current names should make the drawings easy to find. The online shop _should_ have part numbers for all parts too, but those may be missing -- I need to check those.

If you're just browsing, or looking for a part drawing that may match a part you're looking at, I agree that part numbers don't help without a key. I plan to add such a key, either as a file in the repository, or externally (on the ASL wiki). The latter would be nicer, because I could also go into some detail about the intended use of some of the features of the parts.

**Comment by cvoinescu** [comment]
PART-LIST.md added to the repository, with a short description of each part. More to follow (when I have more time).
